a = int(input("Enter 1st Number: "))
b = int(input("Enter 2nd Number: "))
#print(a+b, a-b, a*b, a/b, a//b, a&b, a**b)
print("\nThe Summision is: ", a+b)
print("The Substracton is: ", a-b)
print("The Multiplication is: ", a*b)
print("The Division is: ", a/b)
print("The Floor Division is: ", a//b)
print("The Remainder is: ", a&b)
print("The Power is: ", a**b)